spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://47.107.72.127:3306/shardingsphere
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://47.107.72.127:3306/shardingsphere
        username: root
        password: 123456
        type: com.zaxxer.hikari.HikariDataSource
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    sharding:
      tables:
        table_data:
          actual-data-nodes: ds0.table_data$->{0..4}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: table_data$->{id % 5}